feature-861manmma/environments-support add support for different environments
Xenous-Inc/appostrof-api pull request #1
Opened 2023-02-05 19:30 UTC by slipneff

2023-02-06 01:58 UTC, labamnus commented
.env файлы не надо пушить на гит, они только у разработчиков хранятся

2023-02-06 02:03 UTC, labamnus commented
Плюс смотри, у тебя не будет работать порт из енва, тебе нужно прописать это в main.ts, где происходит запуск приложения

2023-02-06 02:10 UTC, labamnus commented
Ну и папку для конфига в src надо бы перенести

2023-02-06 16:06 UTC, labamnus commented
1) Ты не удалил файлы енва
2) Ты же делал конфиг, а в итоге прокинул просто из енва, какой смысл тогда был. Подумай как правильно прокинуть порт в main.ts

2023-02-06 21:14 UTC, dr3dnought requested changes

2023-02-06 21:14 UTC, dr3dnought commented on development.env
> +DATABASE_PORT=5432
Remove this file from Git!

2023-02-06 21:14 UTC, dr3dnought commented on package.json
>      "start:debug": "nest start --debug --watch",
Set `development` mode for `start:debug` too

2023-02-06 21:14 UTC, dr3dnought commented on production.env
> +DATABASE_PORT=5432
Remove this file from Git!

2023-02-06 21:14 UTC, dr3dnought commented on src/config/configuration.ts
> +        host: process.env.DATABASE_HOST,
We do not have Database host yet. So, remove field `database`

2023-02-06 21:14 UTC, dr3dnought commented on src/config/validation.ts
> +    DATABASE_PORT: Joi.string().required(),
The same issue. Remove it until you reach the corresponding task

2023-02-06 21:14 UTC, dr3dnought commented on src/main.ts
> +import * as process from 'process';
This import is unuseful

2023-02-06 21:14 UTC, dr3dnought commented on src/main.ts
> +    await app.listen(process.env.PORT);
It's better to use `configuration().port`

2023-02-06 21:14 UTC, dr3dnought commented on test.env
> +DATABASE_PORT=5432
Remove this file from Git!

2023-02-06 21:14 UTC, dr3dnought commented on package.json
>      "test": "jest",
Set up `test `environment here

2023-02-07 16:50 UTC, dr3dnought approved these changes

2023-02-07 16:51 UTC, merged