Create 2x auth via Phone calls
Xenous-Inc/appostrof-api pull request #7
Opened 2023-03-15 20:57 UTC by slipneff

2023-03-15 21:09 UTC, dr3dnought requested changes

2023-03-15 21:09 UTC, dr3dnought commented on src/app.module.ts
> +                // },
Make a choice, if you run a prod version, you should enable ssl

2023-03-15 21:09 UTC, dr3dnought commented on src/modules/auth/auth.model.ts
> +    @Column({ type: DataType.BOOLEAN })
Add `defaltValue: false`

2023-03-15 21:09 UTC, dr3dnought commented on src/modules/auth/auth.service.ts
> +                'Content-Type': 'application/json',
You do not need 'Content-Type' here, because you fetch GET request

2023-03-15 21:09 UTC, dr3dnought commented on src/modules/auth/dto/auth.dto.ts
> +    code: number;
Add validation for code

2023-03-16 10:06 UTC, labamnus requested changes

2023-03-16 10:06 UTC, labamnus commented on src/app.module.ts
Make different db names for prod/dev environments

2023-03-16 10:06 UTC, labamnus commented on src/config/configuration.ts
There is no reason to export url's to file

2023-03-16 10:06 UTC, labamnus commented on src/modules/auth/auth.model.ts
> +    user: User;
Why? Check data models

2023-03-16 10:06 UTC, labamnus commented on src/modules/auth/auth.service.ts
> +        const url = `https://api.ucaller.ru/v1.0/initCall?service_id=${configuration().ucaller_id}&key=${
then why env contains this variables......

2023-03-16 10:06 UTC, labamnus commented on src/modules/auth/dto/requestCode.dto.ts
> +    @IsPhoneNumber()
This check contains IsNotEmpty and IsString, you writing overhead code

2023-03-16 10:06 UTC, labamnus commented on src/modules/auth/dto/requestCode.dto.ts
> +    @IsPhoneNumber()
and change it to IsPhoneNumber('RU')

2023-03-16 10:06 UTC, labamnus commented on src/modules/auth/auth.service.ts
> +        if (dto.code != currentConfirmation.code) {
Add validation for isConfirmed == true

2023-03-17 03:57 UTC, labamnus requested changes

2023-03-17 03:57 UTC, labamnus commented on src/modules/auth/auth.service.ts
> +        return currentCode.id;
Name it like 'callId' in response

2023-03-18 04:40 UTC, labamnus approved these changes

2023-03-18 04:40 UTC, merged